[workspace]
authors = ["rifqiharrys <rifqiharrys@proton.me>"]
channels = ["conda-forge"]
name = "sdb-gui"
platforms = ["win-64", "linux-64", "osx-arm64"]
version = "4.1.1"

[tasks]
sdb-gui = { cmd = "python sdb_gui.py", default-environment = "gui", description = "running sdb_gui.py" }
sdb-cli = { cmd = "python cli.py", description = "running cli.py" }

[dependencies]
python = "3.12.*"
numpy = ">=2.4"
pandas = ">=3.0"
scipy = ">=1.17"
xarray = ">=2026.1"
rioxarray = ">=0.20"
geopandas = ">=1.1"
scikit-learn = ">=1.8"
matplotlib = ">=3.10"
joblib = ">=1.5"
typer = ">=0.24.0"

[feature.gui.dependencies]
pyqt = ">=5.15,<6"
pyyaml = ">=6.0"

[feature.exe-build.pypi-dependencies]
auto-py-to-exe = "*"

[feature.notebook.dependencies]
jupyterlab = ">=4.5"

[environments]
gui = ["gui"]
exe-build = ["gui", "exe-build"]
notebook = ["notebook"]
